[package]
name = "api_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
web_viewer = ["rerun/web_viewer"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
glam.workspace = true
itertools = "0.10"
ndarray-rand = "0.14"
ndarray.workspace = true
rand = "0.8"
rerun.workspace = true
