[package]
name = "github_star_history"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
re_log = { workspace = true }
rerun = { workspace = true, features = ["web"] }

anyhow.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
gh-token = "0.1"
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror.workspace = true
